stages:
  - build
  - deploy
jar:
  stage: build
  image: trion/ng-cli
  script:
    - yarn install
    - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build
    #- ng build --prod
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  # Image needs to have ssh-client
  image: docker:git
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - echo $GITLAB_USER_LOGIN
    - echo $CI_JOB_TOKEN
    - echo $CI_REGISTRY
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
